import Head from 'next/head'
import NavMenu, { menuList } from '../navMenu'

import styles from './index.module.css'
import { useState } from 'react'
import Link from 'next/link'

const CommonLayout: React.FC<any> = (props) => {
  const [showMenu, setShowMenu] = useState(false)
  const updateShowMenu = () => setShowMenu((r) => !r)
  return (
    <div>
      <Head>
        <title>Hilton Project</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.header}>
        <NavMenu showMenu={showMenu} updateShowMenu={updateShowMenu} />
      </header>
      <div className={showMenu ? styles.showMenu : styles.disabledMenu}>
        <div>
          <nav className={styles.mobileMenuWrapper}>
            {menuList.map((i) => (
              <Link key={i} href={`/${i}`}>
                {i}
              </Link>
            ))}
          </nav>
        </div>
      </div>
      <main className={styles.main}>{props.children}</main>
    </div>
  )
}

export default CommonLayout
