import Head from 'next/head'
import NavMenu, { menuList } from '../navMenu'

import styles from './index.module.css'
import { useState } from 'react'
import Link from 'next/link'
import { ConnectButton } from '@rainbow-me/rainbowkit'
import { useRouter } from 'next/router'

const CommonLayout: React.FC<any> = (props) => {
  const [showMenu, setShowMenu] = useState(false)
  const updateShowMenu = () => setShowMenu((r) => !r)
  const router = useRouter()
  return (
    <div>
      <Head>
        <title>Hilton Project</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.header}>
        <NavMenu showMenu={showMenu} updateShowMenu={updateShowMenu} />
      </header>
      <div className={showMenu ? styles.showMenu : styles.disabledMenu}>
        <div>
          <nav className={styles.mobileMenuWrapper}>
            {menuList.map((i, index) => (
              <Link
                key={i}
                href={i}
                onClick={updateShowMenu}
                style={{
                  color: router.pathname === i ? '#ff4455' : '#000',
                }}
              >
                {i === '/' ? 'home' : i.replace('/', '')}
              </Link>
            ))}
            {/* <div className={styles.mobileConnectBtn}> */}
            <div>
              <ConnectButton />
            </div>
          </nav>
        </div>
      </div>
      <main className={styles.main}>{props.children}</main>
    </div>
  )
}

export default CommonLayout
