import Head from 'next/head'

import styles from './index.module.css'

const CommonLayout: React.FC<any> = (props) => {
  return (
    <div>
      <Head>
        <title>Hilton Project</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.header}>header</header>
      <main>{props.children}</main>
      <footer className={styles.footer}>footer</footer>
    </div>
  )
}

export default CommonLayout
